=head1 NAME
 
Module::Build::API - API Reference for Alien:: Authors
 
=head1 DESCRIPTION

A list of extra properties and methods provided by 
L<Alien::Base::ModuleBuild> beyond those contained in L<Module::Build::API>.

=head1 AUTHOR

Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>

=head1 SEE ALSO

=over

=item * 

L<Module::Build::API>

=back

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2012 by Joel Berger

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
